name: playa3ull

services:
  pg:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      # insecure credentials for demonstration purposes only
      # these would usually be provided by a secure key store
      POSTGRES_USERNAME: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
